"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env" : "CROWDIN_PERSONAL_TOKEN"
"base_path": "brain-marks/Localization"
"files": [
  {
    "source": "en.lproj/Localizable.strings",                            #source files filter
    "translation": "%two_letters_code%.lproj/Localizable.strings"        #where translations are stored
  }
]
